/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SSI
 */
public class EventExample extends java.awt.Frame {

    /**
     * Creates new form EventExample
     */
    public EventExample() {
        initComponents();
        setSize(500,400);
        ch.add("MP");
        ch.add("MH");
        ch.add("RJ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        ch = new java.awt.Choice();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);
        add(textField1);
        textField1.setBounds(110, 60, 260, 30);

        button1.setLabel("Show");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(170, 150, 47, 24);

        ch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chItemStateChanged(evt);
            }
        });
        add(ch);
        ch.setBounds(110, 220, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        textField1.setText("HELLO...");
    }//GEN-LAST:event_button1ActionPerformed

    private void chItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chItemStateChanged
        // TODO add your handling code here:
        String s=ch.getSelectedItem();
        if(s.equals("MP")){
            setTitle("BHOPAL");
        }else if(s.equals("MH")){
            setTitle("MUMBAI");
        }
    }//GEN-LAST:event_chItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventExample().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Choice ch;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
